version: "3"
services:
  web:
    build: .
    working_dir: /usr/src/app
    ports:
      - "80:80" # set visible port
    networks:
      front-tier:
        ipv4_address: 172.17.0.1

networks:
  front-tier:
    ipam:
      driver: default
      config:
        - subnet: "0.0.0.0/8"
